### PR TITLE
Image ratio

### PR DESCRIPTION
**Pull request by zewlak**
My first commit so be gentle :) Added image_aspect_ratio in generic StructuredMessage.

Sample usage:

`$this->bot->send(new StructuredMessage(
                $recipient,
                StructuredMessage::TYPE_GENERIC,
                [
                    'elements' => $elements,
                    'image_aspect_ratio' => StructuredMessage::IMAGE_ASPECT_RATIO_SQUARE
                ]
            )
        );`

Output:

alt tag

### CODE REVIEW

**Comment by wittfabian** [comment]
Please provide the related link to the facebook docs.

**Comment by zewlak** [comment]
Sure, sorry:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template#payload

**Comment by wittfabian** [comment]
thanks

**Comment by wittfabian** [comment]
How can the attribute be set?

**Comment by zewlak** [comment]
I provided sample usage code in first post.

**Comment by wittfabian** [comment]
Sorry, my mistake.

**Pull request merged**
