### PR TITLE
add appsecret_proof support, useful for post 2.8 api version

### PR DESCRIPTION
**Pull request by gabriel-tandil**
add appsecret_proof support, useful for post 2.8 api version
see [Securing Graph API Requests - Facebook for Developers](https://developers.facebook.com/docs/graph-api/securing-requests/)

### CODE REVIEW

**Comment by wittfabian** [comment]
Has the change been tested?

**Comment by jason-engage** [comment]
bonus, semicolon is fixed.

**Comment by wittfabian** [comment]
TODO: Update CHANGELOG.md

**Comment by gabriel-tandil** [comment]
> Has the change been tested?

Aye aye Sir, well tested :)

**Comment by gabriel-tandil** [comment]
> bonus, semicolon is fixed.

Yeah, that's not a mistake, but it's ugly.
See: [https://www.php.net/manual/es/language.basic-syntax.instruction-separation.php](https://www.php.net/manual/es/language.basic-syntax.instruction-separation.php)

**Comment by gabriel-tandil** [comment]
> TODO: Update CHANGELOG.md

Done

**Comment by o2-web** [comment]
I think it would be cleaner and more beautiful to take app_secret from the config and automatically use it for version v2.8. Thus, we would get rid of the unnecessary parameter in the constructor.
Can We Talk?

**Comment by wittfabian** [comment]
From config?

**Comment by o2-web** [comment]
> From config?
> 
> Sent with [GitHawk](http://githawk.com)

env('FACEBOOK_APP_SECRET');

**Comment by o2-web** [comment]
sorry, I forgot it wasn't just for laravel.

**Pull request merged**
