### PR TITLE
Get user Facebook ID

### PR DESCRIPTION
**Pull request by manhag**
i can use facebook user picture to get facebook user ID

### CODE REVIEW

**Comment by wittfabian** [comment]
The following part is an unreachable statement:

```
$ProfileImage = $this->data['profile_pic'] ;
    $ProfileImagevars = preg_split("#/#", $ProfileImage);
    foreach ($ProfileImagevars as &$value) {
        if (strpos($value, '.jpg') !== false) {
            $JPGPart = $value;
            break;
        }
    }
    $JPGPartsplit = preg_split("#_#",$JPGPart);
    $FacebookID = $JPGPartsplit[1] ;
    return  $FacebookID;
```

You missed the if statement for:
`return !isset($this->data['profile_pic']) ? null;`

**Comment by manhag** [comment]
i edited it now
is it okay ?

**Comment by wittfabian** [comment]
Have you tested the function? Is the user id really returned?

**Comment by wittfabian** [comment]
Check this post:
http://www.tippscout.de/facebook-eigene-id-herausfinden_tipp_5266.html

**Comment by wittfabian** [comment]
I think it's not possible with the link provided by the API.
It's not the same link you get if you click on your profile picture.

**Comment by manhag** [comment]
sorry  .. it is working now

**Comment by wittfabian** [comment]
Can you give me an example for the use of the user id

**Comment by manhag** [comment]
sorry
facebook removed FbID from the user profile picture since 2015 (i noticed this now)

**Comment by wittfabian** [comment]
So, you should use the way over the login.

**Comment by manhag** [comment]
so what is the use of account linking ?

**Comment by wittfabian** [comment]
https://developers.facebook.com/docs/messenger-platform/account-linking

**Comment by manhag** [comment]
thanks a lot bro
so account linking  is used to make login (in my site) using messenger  sender id 
right ??

if i am right .... do you have an example (web page php ) to make this authentication  ?
at this step i will store both PSID and FBID

**Comment by wittfabian** [comment]
The login is indipendent from the sender id. You get the user id as response Back. Everything described in the link

**Pull request closed without merging**
