### PR TITLE
Dev master

### PR DESCRIPTION
**Pull request by jason-engage**
Added TargetAudience setter,getter

Added option to add Tags (to pass 24+1 rule) for certain situations

### CODE REVIEW

**Comment by wittfabian** [comment]
Nice

**Comment by wittfabian** [comment]
Please add the link to the docs!

**Comment by jason-engage** [comment]
Ok sure ... wait, what link and what docs? About Tags I suppose? Gotcha..

**Comment by wittfabian** [comment]
Facebook docs

**Comment by wittfabian** [comment]
Ref:
* https://developers.facebook.com/docs/messenger-platform/send-api-reference/tags
* https://developers.facebook.com/docs/messenger-platform/messenger-profile/target-audience

**Comment by jason-engage** [comment]
I already had the Target Audience links, but I just added the Tags links. Ok now?

**Pull request merged**
