### PR TITLE
Add setStartedButton and deleteStartedButton method.

### PR DESCRIPTION
**Pull request by yuyaun**
doc: https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

### CODE REVIEW

**Comment by yuyaun** [comment]
Update Button template

**Comment by wittfabian** [comment]
Please check the conflicts

**Comment by yuyaun** [comment]
Yes. Resolve the problem

**Comment by wittfabian** [comment]
Is it tested?

**Comment by yuyaun** [comment]
Yes. my service in use

**Comment by wittfabian** [comment]
How is it possible to unlink an account?

The old implementation uses:
`$buttons = new MessageButton( MessageButton::TYPE_ACCOUNT_UNLINK, '');`

**Comment by wittfabian** [comment]
No response, closed!

**Pull request closed without merging**
