### PR TITLE
Added quick_replies option to Image message.

### PR DESCRIPTION
**Pull request by danships**
Hi,

I created the option to add quick replies to an ImageMessage. I have tested it in a project I am developing.

Kind regards.

### CODE REVIEW

**Comment by wittfabian** [comment]
Is this version 1.4 compliant?

**Comment by danships** [comment]
Which version 1.4 do you mean? The FB Api? The Send API reference on Quickreplies states (https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies)

> Quick Replies work with all message types including text message, image and template attachments. Please refer to the Send API documentation for more information on how to use the attachment object.

I was considering using a Trait to add it to all eligible message types, but then the `getData()` function would get too complex in my opinion.

**Comment by wittfabian** [comment]
Messenger Platform v1.4

https://developers.facebook.com/docs/messenger-platform/changelog

#62

**Comment by danships** [comment]
It is 1.4 compliant, but it already existed before 1.4.

**Pull request merged**
