### PR TITLE
add Feature:fb server response handling

### PR DESCRIPTION
**Pull request by kapilkd13**
On sending a message fb server sends either normal response containing receipient_d and message_id or
error message which need to be handled. It can also tell us about the possible
problem and we should act accordingly.
response is received in FbBotApp's call method.
 https://developers.facebook.com/docs/messenger-platform/send-api-reference#errors
referenced from above link

### CODE REVIEW

**Comment by wittfabian** [comment]
This request needs an discussion. The changes affect the syntax a lot.

**Comment by wittfabian** [comment]
#83

**Comment by kapilkd13** [comment]
@wittfabian You are right. Now this code would affect syntax a lot. Actually this PR was sitting idle for a long time. I used it, it worked fine for me and adding this would be a good feature addition.

**Comment by wittfabian** [comment]
Maybe we should Release a stable version (.XY) and add the feature.

**Comment by a-fawzy** [comment]
I do not understand how this feature would affect syntax a lot?

What about adding private member to the FbBotApp Class something like: 
`private $handleMessage;` 
add it to the constructor as an optional parameter with false value as default.
in the send function check it, 
- if false do the same as current 
- if true do the new behavior of handling errors.

**Comment by wittfabian** [comment]
@a-fawzy Your idea is good, but currently not part of the pull request. The current implementation affects the response of the "call"-function. Anyone would have to change their current handling of the returned object.

**Comment by nasirkhan** [comment]
@wittfabian liked the idea of releasing a stable version and add this feature. can we set a tentative date of release?

**Comment by wittfabian** [comment]
No! The current implementation affects the response of the "call"-function. Anyone would have to change their current handling of the returned object.

The idea of @a-fawzy is good, but currently not part of this pull request!

**Comment by jason-engage** [comment]
I really think we need to add these Read receipts. What's the solution here? Should I take a look at this?

**Comment by kapilkd13** [comment]
I would have tested it again, but I am currently not having fb bot setup that I was working with. I am ready to help.

**Comment by wittfabian** [comment]
I would prefer a solution with something like `private $handleMessage`

**Pull request closed without merging**
