### PR TITLE
add Webview support

### PR DESCRIPTION
**Pull request by o2-web**

### CODE REVIEW

**Comment by wittfabian** [comment]
nice

**Comment by wittfabian** [comment]
Have the functions been tested?

**Comment by o2-web** [comment]
@wittfabian , yes it works, but unfortunately "Webview Reference" only works in the mobile app. For browsers will automatically open a new tab to fallback_url

you can see it here http://m.me/1824761117807005 just type `/testing` to bot and click on the button which will appear

sorry for my bad english)

**Comment by wittfabian** [comment]
Yes, webview is only supported within Mobile app

**Pull request merged**
